version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: InsightBridge.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=InsightBridge;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - Seq__ServerUrl=http://seq:5341
    depends_on:
      - db
      - seq

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
      - "5342:5341"
    volumes:
      - seqdata:/data

volumes:
  sqldata:
  seqdata: 